# ==========================================
# compose.yml
#
# | 項目 | 内容 | 備考 |
# | --- | --- | --- |
# | services | 作成したいサービスを列挙 | YAMLはスペース2つ |
# | nginx / db | 作成するサービスの名前 | docker composeで管理する際に必要 |
#
# # 起動手順
# 1. `docker compose up --build -d`
# 2. localhost:${PORT}にアクセス
#
# ==========================================

services:
  nginx:
    # ==========================================
    # nginxサービスの設定項目
    #
    # | 項目 | 内容 | 備考 |
    # | --- | --- | --- |
    # | container_name | コンテナ名 | 外部から見た時の名前 |
    # | hostname | ホスト名 | - |
    # | build | Dockerfileの設定 | - |
    # | volumes | マウントするフォルダ設定(データを永続化) | ホストディレクトリ: コンテナ内ディレクトリ |
    # | restart | コンテナの起動設定 | no unless-stopped always ... |
    # | environment | コンテナ内の環境変数を設定 | Python の `os.environ.get` 等でも取得可能 |
    # | ports | 外部からアクセス可能なポートを設定 | ホストマシンのポート番号:コンテナのポート番号 |
    # | depends_on | サービス間の依存関係を定義 | - |
    # | command | nginxサービスが起動したときに実行するコマンド | - |
    # ==========================================
    env_file: .env
    
    container_name: ${NGINX_CONTAINER_NAME}

    hostname: ${NGINX_CONTAINER_NAME}

    build: 
      # ==========================================
      # Dockerfileの設定項目
      #
      # | 項目 | 内容 |
      # | --- | --- |
      # | context/dockerfile | Dockerfileへの相対パス |
      # | args | Dockerfile内の環境変数を設定 |
      #
      # ==========================================
      context: ${Dockerfile_DIR}
      dockerfile: ${Dockerfile}
      args:
        WS:           ${WS}
        USER_NAME:    ${USER_NAME}
        PASSWORD:     ${PASSWORD}
        ENTRY_DIR:    ${ENTRY_DIR}
        ENTRY_POINT:  ${ENTRY_POINT}
        LANG:         ${LANG}

    volumes:
      - ${VOLUME}:/${ENTRY_DIR}/${WS}

    restart: unless-stopped

    environment:
      # ==========================================
      # コンテナ内の環境変数の設定項目
      #
      # | 項目 | 内容 |
      # | --- | --- |
      # | ${DB_HOST}:${DB_PORT} | データベースコンテナにアクセス |
      # | ${DB_ROOT_USER}/${DB_ROOT_PASSWORD} | データベースコンテナの管理者認証情報 |
      # | ${DB_USER}/${DB_PASSWORD} | データベースコンテナの認証情報 |
      # | ${DB_NAME} | デフォルトで使用するデータベース名 |
      #
      # ==========================================
      - TZ=${TIME_ZONE}
      - LANG=${LANG}
      - DB_HOST=${DB_CONTAINER_NAME}
      - DB_PORT=${DB_PORT}
      - DB_ROOT_USER=root
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    
    ports:
      - "${PORT}:3000"

    depends_on:
      # ==========================================
      # サービス間 依存関係の設定項目
      #
      # | 項目 | 内容 | 備考 |
      # | --- | --- | --- |
      # | db | 依存サービス名 | dbサービス参照 |
      #
      # ==========================================
      db:
        # ==========================================
        # 依存条件設定項目
        #
        # | 項目 | 内容 | 備考 |
        # | --- | --- | --- |
        # | condition | 起動を待ち合わせる条件 | `service_healthy` : `db`の`healthcheck`が成功するまで待つ |
        #
        # ==========================================
        condition: service_healthy

    command:
      - /${ENTRY_DIR}/${ENTRY_POINT}
    

  db:
    # ==========================================
    # dbサービスの設定項目
    #
    # | 項目 | 内容 | 備考 |
    # | --- | --- | --- |
    # | image | 使用するコンテナイメージ | - |
    # | container_name | コンテナ名 | 外部から見た時の名前 |
    # | hostname | ホスト名 | - |
    # | environment | コンテナ内の環境変数を設定 | MySQL公式イメージが参照する環境変数 |
    # | volumes | マウントするフォルダ設定(データを永続化) | ホストディレクトリ: コンテナ内ディレクトリ |
    # | restart | コンテナの起動設定 | no unless-stopped always ... |
    # | healthcheck | - | - |
    # ==========================================
    image: ${DB_IMAGE}

    container_name: ${DB_CONTAINER_NAME}
    hostname: ${DB_CONTAINER_NAME}

    environment:
      - TZ=${TIME_ZONE}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_TCP_PORT=${DB_PORT}
      - MYSQL_DATABASE=${DB_NAME}

    volumes:
      - ${VOLUME}/db:/var/lib/mysql

    restart: unless-stopped

    healthcheck:
      # ==========================================
      # healthcheck の設定項目
      #
      # | 項目 | 内容 | 備考 |
      # | --- | --- | --- |
      # | test | 死活監視に使うコマンド | `mysqladmin ping`でMySQLへの接続可否を確認する |
      # | interval | チェックを実行する間隔 | 5秒ごとに実行 |
      # | timeout | 1回のチェックのタイムアウト時間 | 5秒以内に応答が無ければ失敗扱い |
      # | retries | unhealthy と判定するまでの連続失敗回数 | 10回連続失敗でunhealthy判定 |
      #
      # ==========================================
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10