# ==========================================
# compose.yml
#
# | 項目 | 内容 | 備考 |
# | --- | --- | --- |
# | services | 作成したいコンテナを列挙 | YAMLはスペース2つ |
# | nginx / db | 作成するコンテナの名前 | docker composeで管理する際に必要 |
#
# # 起動手順
# 1. `docker compose up --build -d`
# 2. localhost:${PORT}にアクセス
#
# ==========================================

services:
  nginx:
    # ==========================================
    # nginxコンテナの設定項目
    #
    # | 項目 | 内容 | 備考 |
    # | --- | --- | --- |
    # | container_name | 外部から見た時の名前 | - |
    # | hostname | ホスト名 | - |
    # | build | Dockerfileの設定 | - |
    # | volumes | マウントするフォルダ設定(データを永続化) | ホストディレクトリ: コンテナ内ディレクトリ |
    # | restart | コンテナの起動設定 | no unless-stopped always ... |
    # | environment | コンテナ内の環境変数を設定 | Python の `os.environ.get` 等でも取得可能 |
    # | ports | 外部からアクセス可能なポートを設定 | ホストマシンのポート番号:コンテナのポート番号 |
    # | depends_on | コンテナ間の依存関係を定義 | - |
    # | command | サービスコンテナが起動したときに実行するコマンド | - |
    # ==========================================
    env_file: .env
    
    container_name: ${NGINX_CONTAINER_NAME}

    hostname: ${NGINX_CONTAINER_NAME}

    build: 
      # ==========================================
      # Dockerfileの設定項目
      #
      # | 項目 | 内容 |
      # | --- | --- | --- |
      # | context/dockerfile | Dockerfileへの相対パス |
      # | args | Dockerfile内の環境変数を設定 |
      #
      # ==========================================
      context: ${Dockerfile_DIR}
      dockerfile: ${Dockerfile}
      args:
        WS:           ${WS}
        USER_NAME:    ${USER_NAME}
        PASSWORD:     ${PASSWORD}
        ENTRY_DIR:    ${ENTRY_DIR}
        ENTRY_POINT:  ${ENTRY_POINT}
        LANG:         ${LANG}

    volumes:
      - ${VOLUME}:/${ENTRY_DIR}/${WS}

    restart: unless-stopped

    environment:
      # ==========================================
      # コンテナ内の環境変数の設定項目
      #
      # | 項目 | 内容 |
      # | --- | --- | --- |
      # | ${DB_HOST}:${DB_PORT} | データベースコンテナにアクセス可能にする |
      # | ${DB_USER}/${DB_PASSWORD} | データベースコンテナの認証情報 |
      # | ${DB_NAME} | デフォルトで使用するデータベース名 |
      #
      # ==========================================
      - TZ=${TIME_ZONE}
      - LANG=${LANG}
      - DB_HOST=${DB_CONTAINER_NAME}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    
    ports:
      - "${PORT}:3000"
    
    depends_on:
      db:
        condition: service_healthy         # dbコンテナのヘルスチェックが通ってから起動する

    command:
      - /${ENTRY_DIR}/${ENTRY_POINT}
    

  db:
    # ==========================================
    # dbコンテナの設定項目
    #
    # | 項目 | 内容 | 備考 |
    # | --- | --- | --- |
    # | image | 使用するコンテナイメージ | - |
    # | container_name | 外部から見た時の名前 | - |
    # | hostname | ホスト名 | - |
    # | environment | コンテナ内の環境変数を設定 | MySQL公式イメージが参照する環境変数 |
    # | volumes | マウントするフォルダ設定(データを永続化) | ホストディレクトリ: コンテナ内ディレクトリ |
    # | restart | コンテナの起動設定 | no unless-stopped always ... |
    # | healthcheck | - | - |
    # ==========================================
    image: ${DB_IMAGE}

    container_name: ${DB_CONTAINER_NAME}
    hostname: ${DB_CONTAINER_NAME}

    environment:
      - TZ=${TIME_ZONE}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_TCP_PORT=${DB_PORT}
      - MYSQL_DATABASE=${DB_NAME}

    volumes:
      - ${VOLUME}/db:/var/lib/mysql

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10